@host = http://localhost:5000

###
#   =========================
#   Products
#   =========================
###

POST {{host}}/addProduct
Content-Type: application/json

{
    "name": "Bread",
    "price": 2.75
}

###

POST {{host}}/getAllProducts

###

POST {{host}}/getProduct
Content-Type: application/json

{
    "id": "637e77508bdcc9fe2784df7f"
}

###

POST {{host}}/deleteProduct
Authorization: {{auth_key}}
Content-Type: application/json

{
    "id": "637e78348bdcc9fe2784df8a"
}

###

POST {{host}}/login
Content-Type: application/json

{
    "email": "dawid@gmail.com",
    "password": "12345678"
}

###

POST {{host}}/register
Content-Type: application/json

{
    "email": "dawid@gmail.com",
    "password": "12345678"
}

###

POST {{host}}/logout

###
//==================| CART |=================//
@auth_key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk3Mzg1NTUsImRhdGEiOnsiX2lkIjoiNjM3ZTc4MTc4YmRjYzlmZTI3ODRkZjg1IiwiZW1haWwiOiJkYXdpZEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRhaGtoc0xNRkZiT3RRR0VaNjIycUUuTVZuVHVtR1Y4YlA5UlBFeDlvTC96T1RiQTZyTFkwaSIsImNhcnQiOlt7InByb2R1Y3QiOiI2MzdlNzc1MDhiZGNjOWZlMjc4NGRmN2YiLCJxdWFudGl0eSI6NH0seyJwcm9kdWN0IjoiNjM4MTE3OTVjOGRhYjdhNmRhYWJkZTBlIiwicXVhbnRpdHkiOjF9LHsicHJvZHVjdCI6IjYzODExNzk1YzhkYWI3YTZkYWFiZGUwZSIsInF1YW50aXR5IjoxfV19LCJpYXQiOjE2Njk3Mzc5NTV9.60N0TU4REVZwkMGj2pVBAndnZwklWthBNR7RcyeXPQs
###

POST {{host}}/getCart
Authorization: {{auth_key}}

###

POST {{host}}/addToCart
Authorization: {{auth_key}}
Content-Type: application/json

{
    "id": "63811795c8dab7a6daabde0e"
}

###

POST {{host}}/setProductInCart
Authorization: {{auth_key}}
Content-Type: application/json

{
    "id": "63811795c8dab7a6daabde0e",
    "quantity": 2
}

###

POST {{host}}/removeFromCart
Authorization: {{auth_key}}
Content-Type: application/json

{
    "id": "63811795c8dab7a6daabde0e"
}