@host = http://localhost:5000

###
#   =========================
#   Products
#   =========================
###

POST {{host}}/add_product
Content-Type: application/json

{
    "name": "Milk",
    "price": 30
}

###

POST {{host}}/get_all_products

###

POST {{host}}/get_product
Content-Type: application/json

{
    "id": "637e77508bdcc9fe2784df7f"
}

###

POST {{host}}/delete_product
Authorization: {{auth_key}}
Content-Type: application/json

{
    "id": "637e78348bdcc9fe2784df8a"
}

###

POST {{host}}/login
Content-Type: application/json

{
    "email": "dawid@gmail.com",
    "password": "12345678"
}

###

POST {{host}}/register
Content-Type: application/json

{
    "email": "dawid@gmail.com",
    "password": "12345678"
}

###

POST {{host}}/logout

###
//==================| CART |=================//
@auth_key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjkzMTM4NTgsImRhdGEiOnsiX2lkIjoiNjM3ZTc4MTc4YmRjYzlmZTI3ODRkZjg1IiwiZW1haWwiOiJkYXdpZEBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRhaGtoc0xNRkZiT3RRR0VaNjIycUUuTVZuVHVtR1Y4YlA5UlBFeDlvTC96T1RiQTZyTFkwaSIsImNhcnQiOlt7InF1YW50aXR5IjoxLCJfaWQiOiI2MzdlODIyYzk2ODJlMTMyMmQwNjFiNDQifSx7InF1YW50aXR5IjoxLCJfaWQiOiI2MzdlODIzMTk2ODJlMTMyMmQwNjFiNDkifV19LCJpYXQiOjE2NjkzMTMyNTh9.NC87tQhhn5mowWCqpzGrKCIhB7nLVCxh66GQTMOprfs
###

POST {{host}}/getCart
Authorization: {{auth_key}}

###

POST {{host}}/addToCart
Authorization: {{auth_key}}
Content-Type: application/json

{
    "id": "637e77508bdcc9fe2784df7f"
}

###

POST {{host}}/removeFromCart
Authorization: {{auth_key}}
Content-Type: application/json

{
    "id": "637e77508bdcc9fe2784df7f"
}